services:
  mage:
    build: .
    container_name: mage_tcc_gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: mage start social_sentiment_insights_tcc
    env_file:
      - .env 
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/src/secrets/desafio-estagio-concert-fc29362810a1.json
      
      USER_CODE_PATH: /home/src/social_sentiment_insights_tcc
      
      CUDA_VISIBLE_DEVICES: 0
    ports:
      - "6789:6789"
    volumes:
      - ./:/home/src
      - ./mage_data:/home/src/mage_data
    restart: on-failure