version: 0.1.1
default:
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
  GOOGLE_LOCATION: "US"

mage-pipeline-robot:
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
  GOOGLE_LOCATION: "US"